# Generated by Django 6.0.5 on 2026-06-05 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blog', 'Blog Post'), ('article', 'Article'), ('cover_letter', 'Cover Letter'), ('social', 'Social Media Post'), ('email', 'Email'), ('product_desc', 'Product Description'), ('ad_copy', 'Ad Copy'), ('seo_meta', 'SEO Meta Description'), ('press_release', 'Press Release'), ('script', 'Video Script')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(help_text='System prompt for this content type')),
                ('default_tokens', models.IntegerField(default=500)),
                ('price_per_token', models.DecimalField(decimal_places=6, default=2e-06, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_types',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ContentGenerationTasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('prompt', models.TextField()),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('queued', 'Queued'), ('failed', 'Failed'), ('processing', 'Processing')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Generation parameters')),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tasks', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Ai_Model.contenttype')),
            ],
            options={
                'db_table': 'content_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(related_name='batches', to='Ai_Model.contentgenerationtasks')),
            ],
            options={
                'db_table': 'batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='free', max_length=20)),
                ('monthly_token_limit', models.IntegerField(default=10000)),
                ('monthly_token_used', models.IntegerField(default=0)),
                ('monthly_request_limit', models.IntegerField(default=100)),
                ('monthly_request_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contentgenerationtasks',
            index=models.Index(fields=['status', 'user'], name='content_tas_status_96bdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationtasks',
            index=models.Index(fields=['celery_task_id'], name='content_tas_celery__016fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationtasks',
            index=models.Index(fields=['created_at'], name='content_tas_created_294ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationtasks',
            index=models.Index(fields=['user', 'status', '-created_at'], name='content_tas_user_id_630cde_idx'),
        ),
    ]
