# Generated by Django 4.2.20 on 2026-04-14 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=150, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=170, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('used_2fa', models.BooleanField(default=False)),
                ('otp_code_used', models.CharField(blank=True, max_length=6, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('otp_required', 'OTP Required'), ('otp_failed', 'OTP Failed')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.loginsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_otps',
            },
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', '-login_time'], name='login_sessi_user_id_901e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['session_token'], name='login_sessi_session_854e43_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['ip_address'], name='login_sessi_ip_addr_658e11_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['user', '-created_at'], name='login_logs_user_id_4890f3_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['ip_address'], name='login_logs_ip_addr_669c36_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['status'], name='login_logs_status_c0c84b_idx'),
        ),
    ]
