# Generated by Django 5.2 on 2026-05-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSecurityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_logins', models.IntegerField(default=0)),
                ('successful_logins', models.IntegerField(default=0)),
                ('failed_logins', models.IntegerField(default=0)),
                ('unique_users_logged_in', models.IntegerField(default=0)),
                ('new_users_logged_in', models.IntegerField(default=0)),
                ('suspicious_activities', models.IntegerField(default=0)),
                ('brute_force_attempts', models.IntegerField(default=0)),
                ('blocked_ips', models.IntegerField(default=0)),
                ('mobile_logins', models.IntegerField(default=0)),
                ('desktop_logins', models.IntegerField(default=0)),
                ('tablet_logins', models.IntegerField(default=0)),
                ('unique_locations', models.IntegerField(default=0)),
                ('top_ips', models.JSONField(blank=True, default=list)),
                ('top_devices', models.JSONField(blank=True, default=list)),
                ('hourly_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'login_security_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('multiple_failed', 'Multiple Failed Logins'), ('unusual_location', 'Unusual Location Login'), ('unusual_device', 'Unusual Device Login'), ('unusual_time', 'Unusual Time Login'), ('verification_failed', 'Multiple Verification Failures'), ('account_frozen', 'Account Frozen'), ('password_reset_abuse', 'Password Reset Abuse')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'medium'), (3, 'high'), (4, 'critical')], default=2)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('details', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suspicious_activities',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('alert_type', models.CharField(choices=[('suspicious_login', 'Suspicious Login'), ('brute_force', 'Brute Force Detected'), ('data_breach', 'Potential Data Breach'), ('account_takeover', 'Account Takeover Attempt'), ('api_abuse', 'API Abuse Detected')], max_length=50)),
                ('priority', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suspicious_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.suspiciousactivity')),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['user', '-created_at'], name='suspicious__user_id_2361e2_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['ip_address'], name='suspicious__ip_addr_d22003_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['activity_type'], name='suspicious__activit_9a4782_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['severity'], name='suspicious__severit_b73ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['is_resolved'], name='suspicious__is_reso_80f212_idx'),
        ),
    ]
